### ISSUE TITLE
Knowledge Base Ingestion Error: ValidationException on dataSourceType mismatch

### ISSUE THREAD

**Issue by cagataycali** [strands-agents/agent-builder#9]
## Bug Description
When ingesting documents into a knowledge base, the following error occurs:

```
Error ingesting into knowledge base: An error occurred (ValidationException) when calling the IngestKnowledgeBaseDocuments operation: The dataSourceType that you specified in CUSTOM doesn't match the type of the data source specified in the request header. Check that both types match and retry your request.
```

## Related Information
This issue appears to have been solved in PR #8 (https://github.com/strands-agents/agent-builder/pull/8), but the error is still occurring.

## Environment
- GITHUB_TOKEN is available in the environment

## Example Log
```
list your tools
[...tool list output...]
Error ingesting into knowledge base: An error occurred (ValidationException) when calling the IngestKnowledgeBaseDocuments operation: The dataSourceType that you specified in CUSTOM doesn't match the type of the data source specified in the request header. Check that both types match and retry your request.
```

**Comment by cagataycali** [comment]
Fixed in #8!

**Comment by rbpotter-aws** [comment]
I'm still seeing this behavior:

running:
strands-agents 0.2.1
strands-agents-tools 0.1.8

```
{'status': 'error',
 'content': [{'text': "❌ Error during store operation: An error occurred (ValidationException) when calling the IngestKnowledgeBaseDocuments operation: The dataSourceType that you specified in CUSTOM doesn't match the type of the data source specified in the request header. Check that both types match and retry your request."}],
 'toolUseId': 'tooluse_memory_552170041'}
```

<img width="1747" height="546" alt="Image" src="https://github.com/user-attachments/assets/6af4f770-f502-4da5-b83a-6c95eba0e9a1" />

**Question:** Is it assuming that the knowledge base only has 1 data source for this?
